version: '2'
services:
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    image: telegraf:1.4.4
    environment:
      HOSTNAME: "telegraf-getting-started"
    # Telegraf requires network access to InfluxDB
    links:
      - influxdb
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
      - ./mibs:/root/.snmp/mibs
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
  web:
    build: web
    ports:
      - 5000:5000
    environment:
      - "NSO_URL=http://10.99.163.40:8080"
      - "NSO_USERNAME=admin"
      - "NSO_PASSWORD=admin"

  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    image: influxdb:1.3.7
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/datasources
    environment:
       - "GF_DASHBOARDS_JSON_ENABLED=true"
       - "GF_DASHBOARDS_JSON_PATH=/etc/grafana/dashboards/"
       - "GF_PATHS_DATASOURCES=/etc/grafana/datasources/"
    links:
      - influxdb:influxdb
    depends_on:
      - influxdb

  kapacitor:
    # Full tag list: https://hub.docker.com/r/library/kapacitor/tags/
    image: kapacitor:1.3.3
    volumes:
      # Mount for kapacitor data directory
      - ./kapacitor/data/:/var/lib/kapacitor
      # Mount for kapacitor configuration
      - ./kapacitor/config/:/etc/kapacitor/
    # Kapacitor requires network access to Influxdb
    links:
      - influxdb
    ports:
      # The API for Kapacitor is served on port 9092
      - "9092:9092"
  documentation:
    build:
      context: ./documentation
    ports:
      - "3001:3000"
